// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from "storyblok";
export interface FeatureStoryblok {
  name?: string;
  component: "feature";
  _uid: string;
  [k: string]: any;
}

export interface GanttStoryblok {
  tasks?: (
    | FeatureStoryblok
    | GanttStoryblok
    | GridStoryblok
    | PageStoryblok
    | TaskStoryblok
    | TasksStoryblok
    | TeaserStoryblok
  )[];
  component: "gantt";
  _uid: string;
  [k: string]: any;
}

export interface GridStoryblok {
  columns?: (
    | FeatureStoryblok
    | GanttStoryblok
    | GridStoryblok
    | PageStoryblok
    | TaskStoryblok
    | TasksStoryblok
    | TeaserStoryblok
  )[];
  component: "grid";
  _uid: string;
  [k: string]: any;
}

export interface PageStoryblok {
  body?: (
    | FeatureStoryblok
    | GanttStoryblok
    | GridStoryblok
    | PageStoryblok
    | TaskStoryblok
    | TasksStoryblok
    | TeaserStoryblok
  )[];
  component: "page";
  _uid: string;
  [k: string]: any;
}

export interface TaskStoryblok {
  id?: string;
  name?: string;
  percentDone?: string;
  startDate?: string;
  endDate?: string;
  component: "task";
  _uid: string;
  [k: string]: any;
}

export interface TasksStoryblok {
  task?: (
    | FeatureStoryblok
    | GanttStoryblok
    | GridStoryblok
    | PageStoryblok
    | TaskStoryblok
    | TasksStoryblok
    | TeaserStoryblok
  )[];
  component: "tasks";
  _uid: string;
  [k: string]: any;
}

export interface TeaserStoryblok {
  headline?: string;
  component: "teaser";
  _uid: string;
  [k: string]: any;
}
