import StoryDataProvider from "@/contexts/StoryData.context";
import { apiPlugin, storyblokInit } from "@storyblok/react/rsc";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import StoryblokProvider from "../components/StoryblokProvider";
import "./globals.css";

storyblokInit({
  accessToken: process.env.storyblokApiToken,
  use: [apiPlugin],
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoryDataProvider>
      <StoryblokProvider>
        <html lang="en">
          <body className={inter.className}>{children}</body>
        </html>
      </StoryblokProvider>
    </StoryDataProvider>
  );
}
